# _config.yml

# Site Settings
title: "Dilip Kumara"
description: "The personal portfolio of Dilip Kumara showcasing projects and skills."
url: "https://dilipjp.github.io"   # Your live site URL
baseurl: ""                        # Leave empty if deploying at the root
author: "Dilip Kumara"
timezone: "Asia/Colombo"           # Adjust to your local timezone

# Theme Configuration
theme: jekyll-theme-minimal
show_downloads: false              # Hides download links if not needed

# Build Settings
markdown: kramdown               # Markdown processor
highlighter: rouge               # Syntax highlighter for code blocks

# Exclude from Processing (These files/folders won't be processed by Jekyll)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins (Optional Enhancements)
plugins:
  - jekyll-feed       # Generates an RSS feed for your posts
  - jekyll-seo-tag    # Helps improve SEO with proper meta tags

# Additional Customizations (Optional)
# You can add more settings or custom variables below
# For example, to define social links or custom footer text:
social:
  twitter: "https://twitter.com/yourhandle"
  github: "https://github.com/dilipjp"
  linkedin: "https://www.linkedin.com/in/yourprofile"

footer:
  text: "© 2025 Dilip Kumara. All rights reserved."
